name: CD - Test & Deploy

on:
  push:
    branches: [main]

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "npm" }
      - run: npm install
      - run: npm run test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Render
        run: curl -X POST "https://api.render.com/deploy/srv-d9uptqegekts73d1lehg?key=IUC1ReKn6eY"
